import "../styles/globals.css";
import { Provider } from "react-redux";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/layout";
import { createGlobalStyle } from "styled-components";
import { store } from "../features/redux/store";
import { createWrapper } from "next-redux-wrapper";
import MyErrorBoundary from "../components/Bounderies/ErrorBoundary";

const GlobalStyle = createGlobalStyle`
html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
  box-sizing: border-box;
}
`;


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Simple blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyErrorBoundary>
        <Provider store={store}>
          <GlobalStyle />
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Provider>
      </MyErrorBoundary>
    </>
  );
}
const makeStore = () => store;
export const wrapper = createWrapper(makeStore);
export default wrapper.withRedux(MyApp);
